### PR TITLE
Fix for build on Mac

### PR DESCRIPTION
**Pull request by henryiii**
This is an updated CMakeLists. I changed it to require Root 6, a few more changes needed for compat with both, but shouldn't be hard if needed.

### CODE REVIEW

**Comment by henryiii** [comment]
Should fix #2, as long as Root 6 is okay.

**Comment by willflanagan** [comment]
Hi Henry,
Thanks for the help on this. Is the move to ROOT 6 required to fix the issue? If so, could you please explain further.
Will

**Comment by henryiii** [comment]
Root 5 doesn't seem to work properly with C++11 and Clang, something that Root6 fixes. C++11 is required by Geant 10.2. I get thread-local storage not supported with root 5.

Fixed it so it should work on Linux with Root 5, will submit that change soon to this PR.

**Comment by henryiii** [comment]
This version should now work on root 5 on non-mac (maybe older mac?) systems.

It seems this is a bug fixed in Root 6.02 something:
https://root.cern.ch/phpBB3/viewtopic.php?t=19538

(PS: Try this on 10.10, it might work with root 5)

**Comment by akub19** [comment]
Hi Henry,
Thanks a ton for your help.  With your changes I've successfully built and run on my macbook (Yosemite 10.10.3) with root6.  I'll wait to merge the changes until we can test on the various linux machines where we are doing testing/production runs.
-Andy

**Comment by tjcarroll3** [comment]
I propose tagging what we have now, and creating a branch that then merges Henry's changes for testing.

**Comment by akub19** [comment]
Sounds good to me.

**Comment by henryiii** [comment]
Builds on LoneStar 5 now. Cleaned up the string a little more to not rely on temporaries, and I forgot to add position indep code (For mixing static and shared libraries). You might be able to make the main lib shared instead.

If you can make the code depend on C++11, `std::to_string` is much nicer!

**Comment by henryiii** [comment]
(PS: That's the only linux system I have access to atm with root and Geant builds)

**Comment by tjcarroll3** [comment]
Thanks for all the help. I have merged your changes into our new develop branch. @henryiii

**Pull request closed without merging**
